# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-27 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tip',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
