# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-29 19:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 22, 37, 10, 976446)),
        ),
    ]
