# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-29 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.CharField(max_length=16),
        ),
    ]
