# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_notification_proje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 7, 15, 11, 4, 219440)),
        ),
    ]
