# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-31 07:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_auto_20180807_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 31, 10, 58, 5, 366733)),
        ),
    ]
