# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-02 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_auto_20180831_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 2, 12, 1, 28, 904682)),
        ),
    ]
