# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-16 12:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0016_auto_20180913_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 16, 15, 21, 31, 597399)),
        ),
    ]
