# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-16 12:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0017_auto_20180916_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 16, 15, 25, 6, 849033)),
        ),
    ]
