# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-28 07:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0024_auto_20180917_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 10, 8, 20, 575166)),
        ),
    ]
