# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-28 07:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0025_auto_20180928_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='kisi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notif', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 10, 15, 10, 262268)),
        ),
    ]
