# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-10 09:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0029_auto_20181010_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 12, 14, 13, 104446)),
        ),
    ]
