# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-25 07:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0035_auto_20181022_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 10, 50, 5, 54402)),
        ),
    ]
