# Generated by Django 2.1.3 on 2018-11-11 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0037_auto_20181105_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 11, 17, 1, 25, 414528)),
        ),
    ]
