# Generated by Django 2.1.3 on 2019-03-04 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0039_auto_20190303_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 21, 15, 2, 852072)),
        ),
    ]
