# Generated by Django 2.1.3 on 2019-03-19 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0040_auto_20190304_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 22, 15, 49, 450628)),
        ),
    ]
