# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 15:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='acil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('sonuc', models.TextField()),
                ('acik_kapandi', models.CharField(choices=[('A', 'Açık'), ('K', 'Kapandı')], default='A', max_length=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 2, 5, 18, 37, 48, 890075))),
            ],
        ),
        migrations.CreateModel(
            name='bolum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum_kodu', models.CharField(max_length=10)),
                ('bolum_adi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='denetim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denetim_adi', models.CharField(max_length=100)),
                ('durum', models.CharField(default='A', max_length=1)),
                ('yaratim_tarihi', models.DateField(default=datetime.datetime.today, verbose_name='Date')),
                ('hedef_baslangic', models.DateField()),
                ('hedef_bitis', models.DateField()),
                ('gerc_baslangic', models.DateField(blank=True, null=True)),
                ('gerc_bitis', models.DateField(blank=True, null=True)),
                ('fiili_kapanis', models.DateField(blank=True, null=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('devam_mi', models.BooleanField(default=False)),
                ('tekrar_mi', models.BooleanField(default=False)),
                ('tamamla_mi', models.BooleanField(default=False)),
                ('ilk_dosya', models.FileField(blank=True, null=True, upload_to='raporlar/')),
                ('sonuc_dosya', models.FileField(blank=True, null=True, upload_to='raporlar/')),
                ('denetci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denetci', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='detay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detay_kodu', models.CharField(max_length=5)),
                ('detay_adi', models.CharField(max_length=200)),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.bolum')),
            ],
        ),
        migrations.CreateModel(
            name='grup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grup_adi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='kucukresim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_kucuk', models.ImageField(blank=True, null=True, upload_to='xyz/kucukresim/')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resim_ceken', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denetci', models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], max_length=1)),
                ('denetim_grup_yetkilisi', models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='proje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje_adi', models.CharField(max_length=200)),
                ('ilgililer', models.ManyToManyField(related_name='ilgililer', to=settings.AUTH_USER_MODEL)),
                ('proje_yonetici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yonetici', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sirket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket_adi', models.CharField(max_length=200)),
                ('turu', models.CharField(choices=[('D', 'Denetçi'), ('P', 'Proje')], default='P', max_length=1)),
                ('grubu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.grup')),
            ],
        ),
        migrations.CreateModel(
            name='sonuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayi', models.CharField(choices=[('A', 'Çok İyi'), ('B', 'İyi'), ('C', 'Orta'), ('D', 'Kötü')], default='A', max_length=1)),
                ('aciklama', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='xyz/%Y/%m/%d/', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('tamam', models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='H', max_length=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 2, 5, 18, 37, 48, 887258))),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.bolum')),
                ('denetim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.denetim')),
                ('detay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.detay')),
            ],
        ),
        migrations.CreateModel(
            name='sonuc_bolum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamam', models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='H', max_length=1)),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.bolum')),
                ('denetim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.denetim')),
            ],
        ),
        migrations.CreateModel(
            name='tipi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipi_kodu', models.CharField(max_length=10)),
                ('tipi_adi', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='proje',
            name='sirket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.sirket'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sirket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='islem.sirket'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='denetim',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.proje'),
        ),
        migrations.AddField(
            model_name='denetim',
            name='takipci_many',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='denetim',
            name='tipi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.tipi'),
        ),
        migrations.AddField(
            model_name='denetim',
            name='yaratan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yaratan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bolum',
            name='tipi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.tipi'),
        ),
        migrations.AddField(
            model_name='acil',
            name='denetim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.denetim'),
        ),
    ]
