# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bolum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum_kodu', models.CharField(max_length=10)),
                ('bolum_adi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='detay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detay_kodu', models.CharField(max_length=5)),
                ('detay_adi', models.CharField(max_length=200)),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.bolum')),
            ],
        ),
        migrations.CreateModel(
            name='grup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grup_adi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='musteri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri_adi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='sirket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket_adi', models.CharField(max_length=200)),
                ('grubu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.grup')),
            ],
        ),
        migrations.CreateModel(
            name='tipi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipi_kodu', models.CharField(max_length=10)),
                ('tipi_adi', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='bolum',
            name='tipi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.tipi'),
        ),
    ]
