# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 19:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('islem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denetim',
            name='rutin_mi',
            field=models.CharField(choices=[('R', 'Rutin'), ('P', 'Planlı')], default='P', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sonuc_bolum',
            name='rutindenetci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 5, 22, 58, 29, 191015)),
        ),
        migrations.AlterField(
            model_name='sonuc',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 5, 22, 58, 29, 188326)),
        ),
    ]
