# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 11:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0002_auto_20180205_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='isaretler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bayrak_false', models.BooleanField(default=False)),
                ('bayrak_true', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 14, 35, 57, 955627)),
        ),
        migrations.AlterField(
            model_name='sonuc',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 14, 35, 57, 952897)),
        ),
    ]
