# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0002_auto_20171120_0637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profil',
            new_name='Profile',
        ),
    ]
