# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 12:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0003_auto_20180209_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isaretler',
            old_name='bayrak_true',
            new_name='bolum_listesi_flag',
        ),
        migrations.RemoveField(
            model_name='isaretler',
            name='bayrak_false',
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 15, 0, 56, 289449)),
        ),
        migrations.AlterField(
            model_name='sonuc',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 15, 0, 56, 286706)),
        ),
    ]
