# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('islem', '0003_auto_20171121_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='denetim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denetim_adi', models.CharField(max_length=100)),
                ('durum', models.CharField(max_length=1)),
                ('yaratim_tarihi', models.DateField()),
                ('hedef_baslangic', models.DateField()),
                ('hedef_bitis', models.DateField()),
                ('gerc_baslangic', models.DateField()),
                ('gerc_bitis', models.DateField()),
                ('fiili_kapanis', models.DateField()),
                ('ilk_dosya', models.FileField(upload_to='yuklemeler/')),
                ('sonuc_dosya', models.FileField(upload_to='yuklemeler/')),
                ('denetci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denetci', to=settings.AUTH_USER_MODEL)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.musteri')),
                ('yaratan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yaratan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='gozlemci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denetim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.denetim')),
                ('gozlemci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='icerik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.bolum')),
                ('denetim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.denetim')),
                ('detay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.detay')),
            ],
        ),
        migrations.CreateModel(
            name='sonuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puan', models.IntegerField()),
                ('aciklama', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='cekimler/')),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.bolum')),
                ('denetim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.denetim')),
                ('detay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.detay')),
            ],
        ),
    ]
