# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-10 17:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0004_auto_20180209_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='sonuc_detay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayi', models.CharField(choices=[('A', 'Çok İyi'), ('B', 'İyi'), ('C', 'Orta'), ('D', 'Kötü')], default='A', max_length=1)),
                ('aciklama', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='xyz/%Y/%m/%d/', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('tamam', models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='H', max_length=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 2, 10, 20, 52, 18, 202004))),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.bolum')),
                ('denetim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.denetim')),
                ('detay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.detay')),
            ],
        ),
        migrations.RemoveField(
            model_name='sonuc',
            name='bolum',
        ),
        migrations.RemoveField(
            model_name='sonuc',
            name='denetim',
        ),
        migrations.RemoveField(
            model_name='sonuc',
            name='detay',
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 10, 20, 52, 18, 204660)),
        ),
        migrations.DeleteModel(
            name='sonuc',
        ),
    ]
