# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0004_denetim_gozlemci_icerik_sonuc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icerik',
            name='bolum',
        ),
        migrations.RemoveField(
            model_name='icerik',
            name='denetim',
        ),
        migrations.RemoveField(
            model_name='icerik',
            name='detay',
        ),
        migrations.DeleteModel(
            name='icerik',
        ),
    ]
