# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 06:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('islem', '0005_auto_20180210_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='sonuc_takipci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denetim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.denetim')),
                ('takipci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takipci', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 9, 58, 0, 685293)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 9, 58, 0, 681732)),
        ),
    ]
