# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0005_auto_20171123_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='denetim',
            name='aciklama',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='denetim',
            name='fiili_kapanis',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='denetim',
            name='gerc_baslangic',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='denetim',
            name='gerc_bitis',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='denetim',
            name='ilk_dosya',
            field=models.FileField(blank=True, upload_to='yuklemeler/'),
        ),
        migrations.AlterField(
            model_name='denetim',
            name='sonuc_dosya',
            field=models.FileField(blank=True, upload_to='yuklemeler/'),
        ),
    ]
