# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 06:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0006_auto_20180212_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denetim',
            name='takipci_many',
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 9, 59, 47, 157055)),
        ),
        migrations.AlterField(
            model_name='denetim',
            name='denetci',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denetci', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 9, 59, 47, 153546)),
        ),
    ]
