# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 07:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0007_auto_20180212_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denetim',
            old_name='rutin_mi',
            new_name='rutin_planli',
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 10, 1, 45, 47959)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 10, 1, 45, 44370)),
        ),
    ]
