# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0007_auto_20171123_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonuc',
            name='aciklama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sonuc',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='cekimler/'),
        ),
        migrations.AlterField(
            model_name='sonuc',
            name='puan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
