# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 08:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0008_auto_20180212_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='zon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zon_kodu', models.CharField(max_length=10)),
                ('zon_adi', models.CharField(max_length=200)),
                ('zon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.tipi')),
            ],
        ),
        migrations.RemoveField(
            model_name='bolum',
            name='tipi',
        ),
        migrations.AddField(
            model_name='detay',
            name='puanlama_turu',
            field=models.CharField(choices=[('A', 'Onluk'), ('B', 'Beşlik'), ('C', 'İkilik')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='sonuc_detay',
            name='beslik',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sonuc_detay',
            name='ikilik',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sonuc_detay',
            name='onluk',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sonuc_detay',
            name='puan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 11, 33, 11, 247819)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='sayi',
            field=models.CharField(choices=[('A', 'Onluk'), ('B', 'Beşlik'), ('C', 'İkilik')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 11, 33, 11, 243864)),
        ),

    ]
