# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0008_auto_20171123_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='denetim',
            name='tipi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.tipi'),
            preserve_default=False,
        ),
    ]
