# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 08:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0009_auto_20180219_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolum',
            name='zon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.zon'),
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 11, 41, 2, 486635)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 11, 41, 2, 482151)),
        ),
    ]
