# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0010_sonuc_bolum'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolum',
            name='tamam',
            field=models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='detay',
            name='tamam',
            field=models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='H', max_length=1),
        ),
    ]
