# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 07:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0012_auto_20171127_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonuc',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sonuc',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 10, 47, 46, 857532)),
        ),
        migrations.AddField(
            model_name='sonuc',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sonuc',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sonuc',
            name='foto',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='upload_location', width_field='width_field'),
        ),
    ]
