# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 21:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0013_auto_20171201_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sonuc',
            name='puan',
        ),
        migrations.AddField(
            model_name='sonuc',
            name='sayi',
            field=models.CharField(choices=[('A', 'Çok İyi'), ('B', 'İyi'), ('C', 'Orta'), ('D', 'Kötü')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sonuc',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 0, 14, 15, 261558)),
        ),
    ]
