# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 19:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0014_auto_20180219_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zon',
            old_name='zon',
            new_name='tipi',
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 20, 22, 3, 22, 852946)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 20, 22, 3, 22, 849416)),
        ),
    ]
