# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 07:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0017_auto_20171202_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonuc',
            name='foto',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='xyz/%Y/%m/%d/', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='sonuc',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 4, 10, 39, 38, 960614)),
        ),
    ]
