# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 20:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0019_auto_20180226_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 23, 18, 5, 586328)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='beslik',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='ikilik',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='onluk',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 23, 18, 5, 582860)),
        ),
    ]
