# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 06:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0019_auto_20171205_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonuc',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 9, 53, 2, 643371)),
        ),
    ]
