# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 07:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0020_auto_20180226_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonuc_detay',
            name='resim_varmi',
            field=models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 27, 10, 59, 13, 44635)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 27, 10, 59, 13, 41118)),
        ),
    ]
