# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 16:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0021_auto_20171216_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonuc',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 16, 19, 20, 21, 962869)),
        ),
    ]
