# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 10:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0022_auto_20171216_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='kucukresim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_kucuk', models.ImageField(blank=True, null=True, upload_to='xyz/')),
            ],
        ),
        migrations.AlterField(
            model_name='sonuc',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 18, 13, 13, 20, 3580)),
        ),
    ]
