# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0023_auto_20171218_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kucukresim',
            name='foto_kucuk',
            field=models.FileField(blank=True, null=True, upload_to='xyz/'),
        ),
        migrations.AlterField(
            model_name='sonuc',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 18, 22, 36, 56, 354245)),
        ),
    ]
