# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 18:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('islem', '0024_auto_20171218_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='kucukresim',
            name='kullanici',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resim_ceken', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kucukresim',
            name='foto_kucuk',
            field=models.ImageField(blank=True, null=True, upload_to='xyz/kucukresim/'),
        ),
        migrations.AlterField(
            model_name='sonuc',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 21, 13, 46, 680312)),
        ),
    ]
