# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 13:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0025_auto_20171219_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denetim',
            name='durum',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='denetim',
            name='ilk_dosya',
            field=models.FileField(blank=True, null=True, upload_to='raporlar/'),
        ),
        migrations.AlterField(
            model_name='denetim',
            name='sonuc_dosya',
            field=models.FileField(blank=True, null=True, upload_to='raporlar/'),
        ),
        migrations.AlterField(
            model_name='denetim',
            name='yaratim_tarihi',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='sonuc',
            name='sayi',
            field=models.CharField(choices=[('A', 'Çok İyi'), ('B', 'İyi'), ('C', 'Orta'), ('D', 'Kötü')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='sonuc',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 6, 16, 7, 37, 603919)),
        ),
    ]
