# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 13:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('islem', '0025_auto_20180228_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sonuc_detay',
            name='yazi_varmi',
        ),
        migrations.AddField(
            model_name='denetim',
            name='rapor_yazi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denetim',
            name='rutindenetci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='denetim',
            name='yazi_varmi',
            field=models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 28, 16, 34, 33, 591008)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 28, 16, 34, 33, 587862)),
        ),
    ]
