# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 20:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0026_auto_20180106_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='acil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('sonuc', models.TextField()),
                ('acik_kapandi', models.CharField(choices=[('A', 'Açık'), ('K', 'Kapandı')], default='A', max_length=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 1, 12, 23, 41, 10, 519538))),
                ('denetim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.denetim')),
            ],
        ),
        migrations.AlterField(
            model_name='sonuc',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 23, 41, 10, 516199)),
        ),
    ]
