# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 15:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0026_auto_20180228_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='denetim',
            name='dd_adedi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='denetim',
            name='net_adet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='denetim',
            name='soru_adedi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='denetim',
            name='toplam_puan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sonuc_bolum',
            name='dd_adedi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sonuc_bolum',
            name='net_adet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sonuc_bolum',
            name='soru_adedi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sonuc_bolum',
            name='toplam_puan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 28, 18, 28, 18, 544041)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 28, 18, 28, 18, 540636)),
        ),
    ]
