# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 18:08
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0027_auto_20180228_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='denetim',
            name='ortalama_puan',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='sonuc_bolum',
            name='ortalama_puan',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 28, 21, 8, 37, 707935)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 28, 21, 8, 37, 701526)),
        ),
    ]
