# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-04 11:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0028_auto_20180228_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='qrdosyasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_deger', models.CharField(max_length=10)),
                ('denetim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='islem.denetim')),
            ],
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 14, 41, 43, 140736)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 14, 41, 43, 134845)),
        ),
    ]
