# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-04 13:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0029_auto_20180304_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 16, 12, 44, 423635)),
        ),
        migrations.AlterField(
            model_name='qrdosyasi',
            name='qr_deger',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 16, 12, 44, 417815)),
        ),
    ]
