# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 18:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('islem', '0032_auto_20180312_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ariza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(default=datetime.datetime.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='ariza_tipi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ariza_tipi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='proje_alanlari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alan', models.CharField(max_length=200)),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.proje')),
            ],
        ),

        migrations.CreateModel(
            name='sonuc_denetci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denetci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sonuc_denetci', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sonuc_operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='yer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yer', models.CharField(max_length=200)),
                ('proje_alanlari', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.proje_alanlari')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='operasyon_gorevlisi',
            field=models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profil_resmi',
            field=models.ImageField(blank=True, null=True, upload_to='xyz/profile_resmi/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 21, 42, 29, 859701)),
        ),
        migrations.AlterField(
            model_name='denetim',
            name='rutin_planli',
            field=models.CharField(choices=[('P', 'Planlı'), ('R', 'Rutin'), ('S', 'Sıralı'), ('C', 'Checklist'), ('D', 'İşlem')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 21, 42, 29, 854544)),
        ),
        migrations.AddField(
            model_name='sonuc_operator',
            name='denetim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.denetim'),
        ),
        migrations.AddField(
            model_name='sonuc_operator',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sonuc_denetci',
            name='denetim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.denetim'),
        ),
        migrations.AddField(
            model_name='ariza',
            name='ariza_tipi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.ariza_tipi'),
        ),
        migrations.AddField(
            model_name='ariza',
            name='yer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.yer'),
        ),

    ]
