# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 05:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0034_auto_20180404_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 4, 8, 34, 7, 30209)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 4, 8, 34, 7, 20805)),
        ),
    ]
