# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 09:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0035_auto_20180404_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='detay',
            name='sil',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 13, 12, 42, 5, 473085)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 13, 12, 42, 5, 467796)),
        ),
    ]
