# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-15 15:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0036_auto_20180413_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan_gun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.CharField(choices=[('Pzt', 'Pazartesi'), ('Sal', 'Salı'), ('Çar', 'Çarşamba'), ('Per', 'Perşembe'), ('Cum', 'Cuma'), ('Cmt', 'Cumartesi'), ('Paz', 'Pazar')], max_length=3)),
                ('zaman', models.TimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='yer',
            old_name='yer',
            new_name='yer_adi',
        ),
        migrations.AddField(
            model_name='yer',
            name='yer_mac',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 15, 18, 45, 32, 854979)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 15, 18, 45, 32, 847563)),
        ),
        migrations.AddField(
            model_name='plan_gun',
            name='yer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.yer'),
        ),
    ]
