# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-16 08:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0037_auto_20180415_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 16, 11, 25, 48, 844917)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 16, 11, 25, 48, 837434)),
        ),
    ]
