# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-29 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0040_auto_20180427_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 14, 21, 33, 163551)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 14, 21, 33, 158300)),
        ),
    ]
