# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-29 17:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0043_auto_20180429_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 20, 29, 39, 330085)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 20, 29, 39, 324689)),
        ),
    ]
