# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-29 20:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0046_auto_20180429_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 23, 29, 6, 549823)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 23, 29, 6, 544554)),
        ),
    ]
