# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-25 13:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0050_auto_20180522_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yer',
            old_name='yer_mac',
            new_name='mac_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='operasyon_gorevlisi',
        ),
        migrations.AddField(
            model_name='profile',
            name='isletme_projeyon',
            field=models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='operasyon_merkezyon',
            field=models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='opr_gorev_tipi',
            field=models.CharField(blank=True, choices=[('Opr', 'Operasyon Elemanı'), ('Sef', 'Alan Şefi'), ('Pry', 'Proje Yöneticisi')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='proje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.proje'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 16, 23, 13, 454406)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='denetci',
            field=models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='denetim_grup_yetkilisi',
            field=models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 16, 23, 13, 449066)),
        ),
    ]
