# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 11:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0051_auto_20180525_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 26, 14, 47, 30, 278608)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='proje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='islem.proje'),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 26, 14, 47, 30, 273149)),
        ),
    ]
