# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-27 07:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0054_auto_20180527_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 27, 10, 2, 7, 333118)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 27, 10, 2, 7, 327695)),
        ),
    ]
