# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-27 07:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0055_auto_20180527_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 27, 10, 3, 43, 980216)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 27, 10, 3, 43, 974882)),
        ),
    ]
