# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-01 10:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0059_auto_20180531_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='opr_gorev_tipi',
        ),
        migrations.AddField(
            model_name='profile',
            name='opr_alan_sefi',
            field=models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='opr_proje_yon',
            field=models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 1, 13, 39, 32, 862573)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 1, 13, 39, 32, 857182)),
        ),
    ]
