# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-02 14:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0060_auto_20180601_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 2, 17, 59, 0, 293658)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 2, 17, 59, 0, 288475)),
        ),
    ]
