# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-02 15:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0061_auto_20180602_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 2, 18, 2, 20, 546297)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 2, 18, 2, 20, 541229)),
        ),
    ]
