# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 21:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0063_auto_20180603_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 4, 0, 4, 48, 202318)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 4, 0, 4, 48, 197009)),
        ),
    ]
