# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0064_auto_20180604_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 18, 19, 27, 836152)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 18, 19, 27, 830861)),
        ),
    ]
