# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0065_auto_20180605_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 7, 15, 11, 4, 152365)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 7, 15, 11, 4, 147351)),
        ),
    ]
