# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-07 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0066_auto_20180607_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 7, 17, 16, 50, 974718)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 7, 17, 16, 50, 969602)),
        ),
    ]
