# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-31 07:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0067_auto_20180807_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='sonuc_resim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='xyz/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 31, 10, 58, 5, 299261)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 31, 10, 58, 5, 293370)),
        ),
        migrations.AddField(
            model_name='sonuc_resim',
            name='sonuc_detay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.sonuc_detay'),
        ),
    ]
