# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-02 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0068_auto_20180831_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sonuc_detay',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='sonuc_detay',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='sonuc_detay',
            name='resim_varmi',
        ),
        migrations.RemoveField(
            model_name='sonuc_detay',
            name='width_field',
        ),
        migrations.AddField(
            model_name='sonuc_resim',
            name='resim_kalktimi',
            field=models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 2, 12, 1, 28, 834790)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 2, 12, 1, 28, 828574)),
        ),
    ]
