# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-09 12:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('islem', '0069_auto_20180902_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='spv_yetkilisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.sirket')),
                ('spv_yetkilisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spv_yetkilisi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 15, 16, 17, 94424)),
        ),
        migrations.AlterField(
            model_name='kucukresim',
            name='kullanici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 15, 16, 17, 88632)),
        ),
    ]
