# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-09 18:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0070_auto_20180909_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 21, 5, 34, 214818)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sirket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.sirket'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 21, 5, 34, 209120)),
        ),
    ]
