# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-09 18:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0072_auto_20180909_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 21, 58, 1, 461030)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 21, 58, 1, 455358)),
        ),
    ]
