# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-13 09:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('islem', '0073_auto_20180909_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='den_yetkilisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den_yetkilisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='den_yetkilisi', to=settings.AUTH_USER_MODEL)),
                ('sirket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.sirket')),
            ],
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 12, 28, 45, 86215)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 12, 28, 45, 80270)),
        ),
    ]
