# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-16 12:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0074_auto_20180913_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='operasyon_merkezyon',
            new_name='opr_merkez_yon',
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 16, 15, 21, 31, 526860)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 16, 15, 21, 31, 521346)),
        ),
    ]
