# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-16 12:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0075_auto_20180916_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='opr_admin',
            field=models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 16, 15, 25, 6, 776637)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 16, 15, 25, 6, 770795)),
        ),
    ]
