# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0077_auto_20180917_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 16, 10, 12, 152236)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 16, 10, 12, 144495)),
        ),
    ]
