# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-28 07:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0082_auto_20180917_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='opr_teknik',
            field=models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 10, 8, 20, 505254)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 10, 8, 20, 499792)),
        ),
    ]
