# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-03 07:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0084_auto_20180928_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='yer',
            name='opr_sure',
            field=models.TimeField(default=datetime.time(0, 10)),
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 10, 9, 26, 265503)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 10, 9, 26, 259904)),
        ),
    ]
