# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 07:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0088_auto_20181010_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='eleman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=50)),
                ('soyadi', models.CharField(max_length=50)),
                ('ayrildi', models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='H', max_length=1)),
                ('kull_adi', models.CharField(max_length=100)),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.proje')),
                ('sirket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.sirket')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='ayrildi',
            field=models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 10, 38, 33, 387208)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 10, 38, 33, 381770)),
        ),
    ]
