# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 12:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0089_auto_20181011_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleman',
            name='ayrildi',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ayrildi',
        ),
        migrations.AddField(
            model_name='eleman',
            name='aktifcalisan',
            field=models.CharField(choices=[('E', 'Aktif Çalışan'), ('H', 'Ayrıldı')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='aktifcalisan',
            field=models.CharField(choices=[('E', 'Aktif Çalışan'), ('H', 'Ayrıldı')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 15, 20, 11, 29012)),
        ),
        migrations.AlterField(
            model_name='eleman',
            name='kull_adi',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 15, 20, 11, 23363)),
        ),
    ]
