# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-13 19:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0090_auto_20181011_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 13, 22, 57, 5, 138890)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 13, 22, 57, 5, 131953)),
        ),
    ]
