# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 07:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0092_auto_20181014_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 10, 4, 46, 565664)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 10, 4, 46, 559442)),
        ),
    ]
