# Generated by Django 2.1.3 on 2019-03-19 19:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0098_auto_20190304_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acil',
            name='denetim',
        ),
        migrations.AddField(
            model_name='acil',
            name='proje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.proje'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acil',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 22, 15, 49, 383511)),
        ),
        migrations.AlterField(
            model_name='sonuc_detay',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 22, 15, 49, 377757)),
        ),
    ]
