# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-22 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ariza_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_no', models.CharField(max_length=20)),
                ('tipi', models.CharField(max_length=2)),
                ('rfid_no', models.CharField(max_length=20)),
                ('sebep', models.CharField(max_length=2)),
                ('gelen_tarih', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Denetim_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_no', models.CharField(max_length=20)),
                ('tipi', models.CharField(max_length=2)),
                ('rfid_no', models.CharField(max_length=20)),
                ('kod', models.CharField(max_length=8)),
                ('gelen_tarih', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Operasyon_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_no', models.CharField(max_length=20)),
                ('tipi', models.CharField(max_length=2)),
                ('rfid_no', models.CharField(max_length=20)),
                ('bas_tarih', models.CharField(max_length=30)),
                ('son_tarih', models.CharField(max_length=30)),
                ('bild_tipi', models.CharField(max_length=1)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
