# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-25 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0051_auto_20180525_1623'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webservice', '0002_ariza_data_denetim_data_operasyon_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='rfid_dosyasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_no', models.CharField(max_length=10)),
                ('rfid_tipi', models.CharField(choices=[('O', 'Operasyon'), ('D', 'Diğer')], max_length=1)),
                ('adi', models.CharField(max_length=20)),
                ('soyadi', models.CharField(max_length=20)),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.proje')),
            ],
        ),
        migrations.CreateModel(
            name='yer_updown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_no', models.IntegerField()),
                ('degis', models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='E', max_length=1)),
                ('alive_time', models.DateTimeField(blank=True, null=True)),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.proje')),
            ],
        ),
    ]
