# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0003_rfid_dosyasi_yer_updown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid_dosyasi',
            name='adi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rfid_dosyasi',
            name='rfid_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='rfid_dosyasi',
            name='soyadi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
