# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0005_auto_20180527_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfid_dosyasi',
            old_name='kullanici',
            new_name='calisan',
        ),
    ]
