# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-02 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0061_auto_20180602_1759'),
        ('webservice', '0006_auto_20180531_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='MacPost',
        ),
        migrations.AddField(
            model_name='ariza_data',
            name='proje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.proje'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denetim_data',
            name='proje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.proje'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operasyon_data',
            name='proje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.proje'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ariza_data',
            name='gelen_tarih',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='denetim_data',
            name='gelen_tarih',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='memnuniyet',
            name='gelen_tarih',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='operasyon_data',
            name='bas_tarih',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='operasyon_data',
            name='son_tarih',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
