# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-02 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0062_auto_20180602_1802'),
        ('webservice', '0007_auto_20180602_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='memnuniyet',
            name='proje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.proje'),
            preserve_default=False,
        ),
    ]
