# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0077_auto_20180917_1530'),
        ('webservice', '0008_memnuniyet_proje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sayi_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_no', models.CharField(max_length=20)),
                ('tipi', models.CharField(max_length=2)),
                ('adet', models.CharField(max_length=20)),
                ('gelen_tarih', models.DateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='islem.proje')),
            ],
        ),
    ]
