# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-09 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0012_sayi_data_adet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid_dosyasi',
            name='rfid_tipi',
            field=models.CharField(choices=[('O', 'Operasyon'), ('T', 'Teknik'), ('D', 'Proje Yönetim')], max_length=1),
        ),
    ]
