# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-10 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0087_auto_20181010_1136'),
        ('webservice', '0013_auto_20181009_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza_data',
            name='p_alani',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.proje_alanlari'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ariza_data',
            name='yer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.yer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denetim_data',
            name='p_alani',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.proje_alanlari'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denetim_data',
            name='yer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.yer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memnuniyet',
            name='p_alani',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.proje_alanlari'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memnuniyet',
            name='yer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.yer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operasyon_data',
            name='p_alani',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.proje_alanlari'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operasyon_data',
            name='yer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.yer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sayi_data',
            name='p_alani',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.proje_alanlari'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sayi_data',
            name='yer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.yer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yer_updown',
            name='p_alani',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.proje_alanlari'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yer_updown',
            name='yer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='islem.yer'),
            preserve_default=False,
        ),
    ]
