# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-10 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0014_auto_20181010_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza_data',
            name='kapat',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
