# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0089_auto_20181011_1038'),
        ('webservice', '0015_ariza_data_kapat'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfid_dosyasi',
            name='eleman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='islem.eleman'),
        ),
    ]
