# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-13 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0016_rfid_dosyasi_eleman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfid_dosyasi',
            old_name='calisan',
            new_name='kullanici',
        ),
        migrations.AlterField(
            model_name='rfid_dosyasi',
            name='adi',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rfid_dosyasi',
            name='soyadi',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
