# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0018_auto_20181014_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza_data',
            name='num',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
