# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-25 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0019_ariza_data_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza_data',
            name='rfid_kapat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ariza_data',
            name='rfid_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
