# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kucuk_resim', models.ImageField(upload_to='', verbose_name='kucuk_resim')),
            ],
        ),
    ]
